// <auto-generated />
using System;
using CopeAndHope.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CopeAndHope.Migrations
{
    [DbContext(typeof(CopeAndHopeDbContext))]
    [Migration("20231019161035_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CopeAndHope.Models.CopeEmotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CopeJournalId")
                        .HasColumnType("integer");

                    b.Property<int>("EmotionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CopeJournalId");

                    b.HasIndex("EmotionId");

                    b.ToTable("CopeEmotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CopeJournalId = 1,
                            EmotionId = 1
                        },
                        new
                        {
                            Id = 2,
                            CopeJournalId = 2,
                            EmotionId = 2
                        });
                });

            modelBuilder.Entity("CopeAndHope.Models.CopeJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CopeStrategyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JournalDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("JournalText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CopeStrategyId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("CopeJournals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CopeStrategyId = 3,
                            JournalDate = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JournalText = "This strategy was a tough one for me to implement...",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            CopeStrategyId = 6,
                            JournalDate = new DateTime(2023, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JournalText = "This strategy was easier for me to implement...",
                            UserProfileId = 1
                        });
                });

            modelBuilder.Entity("CopeAndHope.Models.CopeStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CopeStrategyText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CopeStrategies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CopeStrategyText = "Example Coping Strategy 1"
                        },
                        new
                        {
                            Id = 2,
                            CopeStrategyText = "Example Coping Strategy 2"
                        },
                        new
                        {
                            Id = 3,
                            CopeStrategyText = "Example Coping Strategy 3"
                        },
                        new
                        {
                            Id = 4,
                            CopeStrategyText = "Example Coping Strategy 4"
                        },
                        new
                        {
                            Id = 5,
                            CopeStrategyText = "Example Coping Strategy 5"
                        },
                        new
                        {
                            Id = 6,
                            CopeStrategyText = "Example Coping Strategy 6"
                        },
                        new
                        {
                            Id = 7,
                            CopeStrategyText = "Example Coping Strategy 7"
                        },
                        new
                        {
                            Id = 8,
                            CopeStrategyText = "Example Coping Strategy 8"
                        },
                        new
                        {
                            Id = 9,
                            CopeStrategyText = "Example Coping Strategy 9"
                        },
                        new
                        {
                            Id = 10,
                            CopeStrategyText = "Example Coping Strategy 10"
                        },
                        new
                        {
                            Id = 11,
                            CopeStrategyText = "Example Coping Strategy 11"
                        },
                        new
                        {
                            Id = 12,
                            CopeStrategyText = "Example Coping Strategy 12"
                        },
                        new
                        {
                            Id = 13,
                            CopeStrategyText = "Example Coping Strategy 13"
                        },
                        new
                        {
                            Id = 14,
                            CopeStrategyText = "Example Coping Strategy 14"
                        },
                        new
                        {
                            Id = 15,
                            CopeStrategyText = "Example Coping Strategy 15"
                        },
                        new
                        {
                            Id = 16,
                            CopeStrategyText = "Example Coping Strategy 16"
                        },
                        new
                        {
                            Id = 17,
                            CopeStrategyText = "Example Coping Strategy 17"
                        },
                        new
                        {
                            Id = 18,
                            CopeStrategyText = "Example Coping Strategy 18"
                        },
                        new
                        {
                            Id = 19,
                            CopeStrategyText = "Example Coping Strategy 19"
                        },
                        new
                        {
                            Id = 20,
                            CopeStrategyText = "Example Coping Strategy 20"
                        },
                        new
                        {
                            Id = 21,
                            CopeStrategyText = "Example Coping Strategy 21"
                        },
                        new
                        {
                            Id = 22,
                            CopeStrategyText = "Example Coping Strategy 22"
                        },
                        new
                        {
                            Id = 23,
                            CopeStrategyText = "Example Coping Strategy 23"
                        },
                        new
                        {
                            Id = 24,
                            CopeStrategyText = "Example Coping Strategy 24"
                        },
                        new
                        {
                            Id = 25,
                            CopeStrategyText = "Example Coping Strategy 25"
                        },
                        new
                        {
                            Id = 26,
                            CopeStrategyText = "Example Coping Strategy 26"
                        },
                        new
                        {
                            Id = 27,
                            CopeStrategyText = "Example Coping Strategy 27"
                        },
                        new
                        {
                            Id = 28,
                            CopeStrategyText = "Example Coping Strategy 28"
                        },
                        new
                        {
                            Id = 29,
                            CopeStrategyText = "Example Coping Strategy 29"
                        },
                        new
                        {
                            Id = 30,
                            CopeStrategyText = "Example Coping Strategy 30"
                        },
                        new
                        {
                            Id = 31,
                            CopeStrategyText = "Example Coping Strategy 31"
                        });
                });

            modelBuilder.Entity("CopeAndHope.Models.Emotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmotionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Emotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmotionName = "Hopeful"
                        },
                        new
                        {
                            Id = 2,
                            EmotionName = "Empowered"
                        },
                        new
                        {
                            Id = 3,
                            EmotionName = "Optimistic"
                        },
                        new
                        {
                            Id = 4,
                            EmotionName = "Calm"
                        },
                        new
                        {
                            Id = 5,
                            EmotionName = "Gracious"
                        },
                        new
                        {
                            Id = 6,
                            EmotionName = "Joyful"
                        });
                });

            modelBuilder.Entity("CopeAndHope.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Admina",
                            IdentityUserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            LastName = "Strator"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Ryan",
                            IdentityUserId = "d8d76512-74f1-43bb-b1fd-87d3a8aa36df",
                            LastName = "Mathis"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Ethan",
                            IdentityUserId = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            LastName = "Mathis"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Simone",
                            IdentityUserId = "c806cfae-bda9-47c5-8473-dd52fd056a9b",
                            LastName = "Henderson"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Bob",
                            IdentityUserId = "9ce89d88-75da-4a80-9b0d-3fe58582b8e2",
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Eve",
                            IdentityUserId = "d224a03d-bf0c-4a05-b728-e3521e45d74d",
                            LastName = "Davis"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35",
                            ConcurrencyStamp = "d01b49db-2e7e-46af-a901-8251ae673d45",
                            Name = "Admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "47960b3d-ca08-4fbe-9876-15119b0b4880",
                            Email = "admina@strator.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAENDq0T5FbYROiTavVwdXG1f2XP/drbg0ddPGD7s6pnAVXQo34hqFWxOOBz5OexDXnw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "48657560-3523-41fb-89fd-3562043c1a2c",
                            TwoFactorEnabled = false,
                            UserName = "Administrator"
                        },
                        new
                        {
                            Id = "d8d76512-74f1-43bb-b1fd-87d3a8aa36df",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "74633978-1336-4ad2-a410-ed37fc4352ca",
                            Email = "ryan@mathis.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEMtTnshMzZka3Y5GdpQP+dwuXdH84rFGW+nqxq+bIrx9T7KUGEHxOB9Llnxwpl7e9Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3a8486a4-becd-403d-858b-0083a19ca004",
                            TwoFactorEnabled = false,
                            UserName = "RyanMathis"
                        },
                        new
                        {
                            Id = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cacfd477-1a19-4455-9e29-b44fe51b046c",
                            Email = "ethan@mathis.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEOnd3iG4mqoFSH8bilYcmeb2LdOXVRdPvgJX6H+kA27DS3iuSZvSdOmiTTdujPLolA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "62c28541-d9d0-43ad-b063-69acbc71d9e8",
                            TwoFactorEnabled = false,
                            UserName = "EthanMathis"
                        },
                        new
                        {
                            Id = "c806cfae-bda9-47c5-8473-dd52fd056a9b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cc7a34ea-6fc4-430a-8ff7-091c583882dc",
                            Email = "simone@henderson.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEMwpBTnyPQ2FH5qS8vwebYydXPFGOrHsrD6vGABLZP4ChJDBOlUu1WTnAMDOSG2AIg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1e4335d3-e435-43c5-8aab-43810914335b",
                            TwoFactorEnabled = false,
                            UserName = "SimoneHenderson"
                        },
                        new
                        {
                            Id = "9ce89d88-75da-4a80-9b0d-3fe58582b8e2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "361c7d60-74e0-45ee-b498-303e8475ed6c",
                            Email = "bob@williams.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAELz4baWQn7VLj4I184wqk46/SqkHjhg9Ov13R2ZnF+Z+/ZpHeR7dN94vONM5GrCbbw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2745112d-cca2-46ba-859a-64cfd776c08d",
                            TwoFactorEnabled = false,
                            UserName = "BobWilliams"
                        },
                        new
                        {
                            Id = "d224a03d-bf0c-4a05-b728-e3521e45d74d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "707aa808-6894-4eff-aed4-6e5bed957ff9",
                            Email = "Eve@Davis.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFTOkRAvH5xHIpXiIcz/t3TxPNRTSsPIKpfIJnb6wlDbuwz3pfPcAKrstXXaz+WWig==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "49818934-a75a-406d-98f4-8d7fa952b865",
                            TwoFactorEnabled = false,
                            UserName = "EveDavis"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            RoleId = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35"
                        },
                        new
                        {
                            UserId = "d8d76512-74f1-43bb-b1fd-87d3a8aa36df",
                            RoleId = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CopeAndHope.Models.CopeEmotion", b =>
                {
                    b.HasOne("CopeAndHope.Models.CopeJournal", "CopeJournal")
                        .WithMany("CopeEmotions")
                        .HasForeignKey("CopeJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CopeAndHope.Models.Emotion", "Emotion")
                        .WithMany()
                        .HasForeignKey("EmotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CopeJournal");

                    b.Navigation("Emotion");
                });

            modelBuilder.Entity("CopeAndHope.Models.CopeJournal", b =>
                {
                    b.HasOne("CopeAndHope.Models.CopeStrategy", "CopeStrategy")
                        .WithMany("CopeJournals")
                        .HasForeignKey("CopeStrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CopeAndHope.Models.UserProfile", "UserProfile")
                        .WithMany("CopeJournals")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CopeStrategy");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("CopeAndHope.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId");

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CopeAndHope.Models.CopeJournal", b =>
                {
                    b.Navigation("CopeEmotions");
                });

            modelBuilder.Entity("CopeAndHope.Models.CopeStrategy", b =>
                {
                    b.Navigation("CopeJournals");
                });

            modelBuilder.Entity("CopeAndHope.Models.UserProfile", b =>
                {
                    b.Navigation("CopeJournals");
                });
#pragma warning restore 612, 618
        }
    }
}
